import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <ThemeProvider theme={theme}>
          <body className="bg-slate-200">{children}</body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
